server:
  port: 8008

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/shop_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&zeroDateTimeBehavior=convertToNull
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username:  root
    password:  root